package org.nocoder.model;

public class ArticleWithBLOBs extends Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.PREVIEW
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private byte[] preview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CONTENT
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.PREVIEW
     *
     * @return the value of article.PREVIEW
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public byte[] getPreview() {
        return preview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.PREVIEW
     *
     * @param preview the value for article.PREVIEW
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setPreview(byte[] preview) {
        this.preview = preview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CONTENT
     *
     * @return the value of article.CONTENT
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CONTENT
     *
     * @param content the value for article.CONTENT
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}