package org.nocoder.model;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.TITLE
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.AUTHOR
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.TAG
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.CREATE_TIME
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.TITLE
     *
     * @return the value of article.TITLE
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.TITLE
     *
     * @param title the value for article.TITLE
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.AUTHOR
     *
     * @return the value of article.AUTHOR
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.AUTHOR
     *
     * @param author the value for article.AUTHOR
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.TAG
     *
     * @return the value of article.TAG
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.TAG
     *
     * @param tag the value for article.TAG
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.CREATE_TIME
     *
     * @return the value of article.CREATE_TIME
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.CREATE_TIME
     *
     * @param createTime the value for article.CREATE_TIME
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.UPDATE_TIME
     *
     * @return the value of article.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.UPDATE_TIME
     *
     * @param updateTime the value for article.UPDATE_TIME
     *
     * @mbggenerated Sat Apr 02 18:02:05 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}