server:
  port: 8080
# database
jdbc_driver: org.sqlite.JDBC
jdbc_url: jdbc:sqlite:/Users/jason/local/git/nocoder/data/db/freda.db

logging:
  level:
    org.nocoder: debug
  file: freda.log
spring:
  output:
    ansi:
      enabled: detect
