server:
  port: 8080
# database
jdbc.driver: org.sqlite.JDBC
jdbc.url: jdbc:sqlite:/Users/jason/local/git/nocoder/data/freda_blog.db

# redis
redis_server_host: 127.0.0.1
redis_server_port: 6379
redis_server_auth:
