server:
  port: 81
# database
jdbc_driver: org.sqlite.JDBC
jdbc_url: jdbc:sqlite:/Users/jason/local/github/nocoder/data/db/freda.db

logging:
  level:
    org.nocoder: debug
  file: freda.log
spring:
  output:
    ansi:
      enabled: detect
